// <auto-generated />
using System;
using GlobalSolution2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace GlobalSolution2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251112172916_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GlobalSolution2.Models.Competencia", b =>
                {
                    b.Property<int>("CompetenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_COMPETENCIA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompetenciaId"));

                    b.Property<string>("CategoriaCompetencia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("CATEGORIA_COMPETENCIA");

                    b.Property<string>("DescricaoCompetencia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("DESCRICAO_COMPETENCIA");

                    b.Property<string>("NomeCompetencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME_COMPETENCIA");

                    b.HasKey("CompetenciaId");

                    b.ToTable("COMPETENCIA");
                });

            modelBuilder.Entity("GlobalSolution2.Models.Recomendacao", b =>
                {
                    b.Property<int>("RecomendacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_RECOMENDACAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecomendacaoId"));

                    b.Property<DateTime>("DataRecomendacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_RECOMENDACAO");

                    b.Property<string>("DescricaoRecomendacao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("DESCRICAO_RECOMENDACAO");

                    b.Property<string>("PromptUsado")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("PROMPT_USADO");

                    b.Property<string>("TituloRecomendacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TITULO_RECOMENDACAO");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USUARIO_ID_USUARIO");

                    b.HasKey("RecomendacaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RECOMENDACAO", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("GlobalSolution2.Models.RegistroBemEstar", b =>
                {
                    b.Property<int>("RegistroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_REGISTRO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistroId"));

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_REGISTRO");

                    b.Property<int>("HorasSono")
                        .HasPrecision(2)
                        .HasColumnType("NUMBER(2,0)")
                        .HasColumnName("HORAS_SONO");

                    b.Property<int>("HorasTrabalho")
                        .HasPrecision(2)
                        .HasColumnType("NUMBER(2,0)")
                        .HasColumnName("HORAS_TRABALHO");

                    b.Property<string>("HumorRegistro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("HUMOR_REGISTRO");

                    b.Property<int>("NivelEnergia")
                        .HasPrecision(2)
                        .HasColumnType("NUMBER(2,0)")
                        .HasColumnName("NIVEL_ENERGIA");

                    b.Property<int>("NivelEstresse")
                        .HasPrecision(2)
                        .HasColumnType("NUMBER(2,0)")
                        .HasColumnName("NIVEL_ESTRESSE");

                    b.Property<string>("ObservacaoRegistro")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("OBSERVACAO_REGISTRO");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USUARIO_ID_USUARIO");

                    b.HasKey("RegistroId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("REGISTRO_BEM_ESTAR");
                });

            modelBuilder.Entity("GlobalSolution2.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("AreaAtual")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("AREA_ATUAL");

                    b.Property<string>("AreaInteresse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("AREA_INTERESSE");

                    b.Property<string>("NivelExperiencia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NIVEL_EXPERIENCIA");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME_USUARIO");

                    b.Property<string>("ObjetivoCarreira")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("OBJETIVO_CARREIRA");

                    b.Property<string>("SenhaUsuario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("SENHA_USUARIO");

                    b.HasKey("UsuarioId");

                    b.HasIndex("NomeUsuario")
                        .IsUnique();

                    b.ToTable("USUARIO");
                });

            modelBuilder.Entity("UsuarioCompetencia", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USUARIO_ID_USUARIO")
                        .HasColumnOrder(0);

                    b.Property<int>("CompetenciaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("COMPETENCIA_ID_COMPETENCIA")
                        .HasColumnOrder(1);

                    b.HasKey("UsuarioId", "CompetenciaId");

                    b.HasIndex("CompetenciaId");

                    b.ToTable("USUARIO_COMPETENCIA");
                });

            modelBuilder.Entity("GlobalSolution2.Models.RecomendacaoProfissional", b =>
                {
                    b.HasBaseType("GlobalSolution2.Models.Recomendacao");

                    b.Property<string>("AreaRecomendacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("AREA_RECOMENDACAO");

                    b.Property<string>("CategoriaRecomendacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("CATEGORIA_RECOMENDACAO");

                    b.Property<string>("FonteRecomendacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("FONTE_RECOMENDACAO");

                    b.ToTable("RECOMENDACAO_PROFISSIONAL", (string)null);
                });

            modelBuilder.Entity("GlobalSolution2.Models.RecomendacaoSaude", b =>
                {
                    b.HasBaseType("GlobalSolution2.Models.Recomendacao");

                    b.Property<string>("MensagemSaude")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("MENSAGEM_SAUDE");

                    b.Property<string>("NivelAlerta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NIVEL_ALERTA");

                    b.Property<string>("TipoSaude")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TIPO_SAUDE");

                    b.ToTable("RECOMENDACAO_SAUDE", (string)null);
                });

            modelBuilder.Entity("GlobalSolution2.Models.Recomendacao", b =>
                {
                    b.HasOne("GlobalSolution2.Models.Usuario", "Usuario")
                        .WithMany("Recomendacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GlobalSolution2.Models.RegistroBemEstar", b =>
                {
                    b.HasOne("GlobalSolution2.Models.Usuario", "Usuario")
                        .WithMany("RegistrosBemEstar")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("UsuarioCompetencia", b =>
                {
                    b.HasOne("GlobalSolution2.Models.Competencia", "Competencia")
                        .WithMany("UsuarioCompetencias")
                        .HasForeignKey("CompetenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlobalSolution2.Models.Usuario", "Usuario")
                        .WithMany("UsuarioCompetencias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competencia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GlobalSolution2.Models.RecomendacaoProfissional", b =>
                {
                    b.HasOne("GlobalSolution2.Models.Recomendacao", null)
                        .WithOne()
                        .HasForeignKey("GlobalSolution2.Models.RecomendacaoProfissional", "RecomendacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GlobalSolution2.Models.RecomendacaoSaude", b =>
                {
                    b.HasOne("GlobalSolution2.Models.Recomendacao", null)
                        .WithOne()
                        .HasForeignKey("GlobalSolution2.Models.RecomendacaoSaude", "RecomendacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GlobalSolution2.Models.Competencia", b =>
                {
                    b.Navigation("UsuarioCompetencias");
                });

            modelBuilder.Entity("GlobalSolution2.Models.Usuario", b =>
                {
                    b.Navigation("Recomendacoes");

                    b.Navigation("RegistrosBemEstar");

                    b.Navigation("UsuarioCompetencias");
                });
#pragma warning restore 612, 618
        }
    }
}
